using BankTransferService.Interfaces;
using BankTransferService.Models.Domain;
using BankTransferService.Models.Requests;
using BankTransferService.Models.Responses;
using Microsoft.AspNetCore.Mvc;

namespace BankTransferService.Controllers;

/// <summary>
/// Handles money transfer requests.
/// </summary>
[ApiController]
[Route("api/transfers")]
public class TransfersController : ControllerBase
{
    private readonly ITransferService _transferService;

    public TransfersController(ITransferService transferService)
    {
        _transferService = transferService;
    }

    /// <summary>
    /// Executes a money transfer between two accounts.
    /// </summary>
    /// <param name="request">Transfer details (accounts, amount, reference, description).</param>
    /// <param name="idempotencyKey">
    /// Optional. When provided and a transfer with this key has already been completed,
    /// the existing transfer is returned and no new transfer is created. Use a stable, unique
    /// value per logical operation (e.g. a UUID generated by the caller).
    /// </param>
    [HttpPost]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> CreateTransfer(
        [FromBody] TransferRequest request,
        [FromHeader(Name = "Idempotency-Key")] string? idempotencyKey = null
    )
    {
        if (!ModelState.IsValid)
            return BadRequest(ModelState);

        var result = await _transferService.ExecuteTransferAsync(request, idempotencyKey);

        return result.Status switch
        {
            TransferStatus.Success => StatusCode(
                StatusCodes.Status201Created,
                new TransferCreatedResponse { TransferId = result.TransferId!.Value }
            ),
            TransferStatus.NotFound => NotFound(
                new ErrorResponse { Message = result.ErrorMessage! }
            ),
            TransferStatus.ServerError => StatusCode(
                StatusCodes.Status500InternalServerError,
                new ErrorResponse { Message = result.ErrorMessage! }
            ),
            _ => BadRequest(new ErrorResponse { Message = result.ErrorMessage! }),
        };
    }
}
